### ISSUE TITLE
Enzyme tracking issue

### ISSUE THREAD

**Issue by ZuseZ4** [EnzymeAD/rust#1]
Based on our HackMD, steps in order to differentiate code using this rust fork. First iteration:

- [x] Add enzyme flag to x.py. Propagate that flag trough. We only request it at build time, not when running cargo/rustc.
        Usage: `./configure --enable-llvm-link-shared --enable-llvm-plugins --enable-llvm-enzyme --release-channel=nightly --enable-llvm-assertions --enable-clang --enable-lld --enable-option-checking --enable-ninja` and `x build --stage 1`

- [x]  Add enzyme as tree along with pre-build wrappers conditionally.

- [x] Add a trait file to `rustc_codegen_ssa/src/traits/autodiff.rs` @ZuseZ4, @bytesnake 

- [x]  Write a special proc-macro which ~ follows this poc [here](https://github.com/zuseZ4/autodiff), Add a hidden node similar to the asm macro and propagate the macro "parameters" trough. @bytesnake 

- [ ] Tighten macro assertions if possible, drop `extern "C"` generation, further improvements.  @bytesnake 

- [x]  Add (cfg-gated) code in `rustc_codegen_llvm/src/lib.rs` and `rustc_codegen_ssa/src/back/write.rs` to differentiate full-LTO builds.

- [ ]  Testing

Notes / changes:
- Only toggle Enzyme at build time, not trough cargo / rustc. Reason: Should become a always available default features.
- Add pre-build wrappers: Allows us to not add the bindgen dependency to rust-lang/rust, will also stay constant for each enzyme added as a tree. We can easily update bindings by activating the bindgen features trough cargo.

**Comment by ZuseZ4** [comment]
It basically works by now, though it could need some more love.
Let's close this one and add more specific ones for the rest which we still need to do.
